name = "IndexableIterators"
uuid = "b43d572c-a086-4fde-aa68-3fee98ab3ce3"
authors = ["jishnub <jishnub@users.noreply.github.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
